defaults:
  - default

name: tabtransformer

estimator:
  _target_: pytorch_tabular.models.TabTransformerConfig
  head_config:
    layers: 128-128
    dropout: 0.1
  metrics_params:
    - num_classes: 7
    - num_classes: 7
    - num_classes: 7
